version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    networks:
      - springmysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: VPA_db
      MYSQL_USER: VPA_user
      MYSQL_PASSWORD: heslo22
    ports:
      - "3306:3306"
  app:
    build: .
#    container_name: vpa-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/VPA_db
      SPRING_DATASOURCE_USERNAME: VPA_user
      SPRING_DATASOURCE_PASSWORD: heslo22
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - springmysql





  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"

networks:
  springmysql:

